# SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
# SPDX-License-Identifier: MIT

# brew tap messense/macos-cross-toolchains
# brew install aarch64-unknown-linux-gnu
CONFIG_TOOLCHAIN_PREFIX="aarch64-unknown-linux-gnu-"

CONFIG_LVGL_COMPONENT_ENABLED=y
CONFIG_LVGL_9_5_SRC=y
CONFIG_V9_5_LV_CONF_MINIMAL=y
CONFIG_V9_5_LV_USE_LABEL=y

CONFIG_V9_5_LV_USE_CLIB_MALLOC=y
CONFIG_V9_5_LV_USE_CLIB_STRING=y
CONFIG_V9_5_LV_USE_CLIB_SPRINTF=y

CONFIG_V9_5_LV_FONT_DEFAULT_MONTSERRAT_14=y
CONFIG_V9_5_LV_FONT_MONTSERRAT_14=y

CONFIG_V9_5_LV_OS_PTHREAD=y
CONFIG_V9_5_LV_USE_LINUX_FBDEV=y
CONFIG_V9_5_LV_USE_EVDEV=y
CONFIG_V9_5_LV_DRAW_SW_ASM_NEON=y
CONFIG_V9_5_LV_USE_DRAW_SW_ASM=1
